scikit-build/ninja-python-distributions

- scikit-ci.yml
Specifying -U ensures "setuptools>=28.0.0" required by scikit-build is
installed and fixes "cannot import name 'monkey'" error.
> ci: Fix py33 and 34 build error ensuring all dependencies are up-to-date

- scikit-ci.yml
This is workaround waiting scikit-build/scikit-build#247 is addressed.
See https://github.com/MacPython/wiki/wiki/Spinning-wheels#question-will-pip-give-me-a-broken-wheel
> travis: Ensure MacOSX wheels can be installed on MacOSX >= 10.6

- requirements-dev.txt
- tests/test_distribution.py
The pattern argument to listdir() has been deprecated in favor of the
match argument. They don't function in the exact same way as match
expects a callable that will be used for matching.
> Pass match rather than pattern argument to files()

- NinjaUrls.cmake
- README.rst
- docs/update_ninja_version.rst
- tests/test_distribution.py
Not much to say really. Just update the ninja binaries to the latest version.
> Update ninja to 1.9.0.g5b44b.kitware.dyndep-1.jobserver-1

- pyproject.toml
Co-authored-by: Ondřej Čertík <ondrej@certik.us>
> Add pyproject.toml to ensure pip will download scikit-build when building from source

- NinjaUrls.cmake
> Update to Ninja 1.10.0.gfb670.kitware.jobserver-1 to include signed windows executable

- .travis.yml
- pyproject.toml
- requirements-dev.txt
- scikit-ci.yml
- setup.py
- versioneer.py
- Fix macOS build on travis-ci
Same fix as https://github.com/scikit-build/cmake-python-distributions/pull/131
This should fix the build issues seen in #40
- Fix Linux build on circleci
Same fix as https://github.com/scikit-build/cmake-python-distributions/pull/128
- Fix source build
Same fix as https://github.com/scikit-build/cmake-python-distributions/pull/114 +
Add CMake to build dependencies +
Add current folder to sys.path in setup.py +
Update versioneer versioning scheme when `post` is present in the closest tag
> ci: fix builds

- setup.py
This fixes metadata checks when running `twine check dist/*`
> fix: add long_description_content_type to setup

- .circleci/config.yml
- .travis.yml
- appveyor.yml
- constraints.txt
- scripts/convert_to_generic_platform_wheel.py
- scripts/manylinux2014-aarch64-build-and-test-wheel.sh
This prepares for `universal2` wheels and allows to create `py2.py3` wheels
> chore: use same `convert_to_generic_platform_wheel.py` script as cmake

- CONTRIBUTING.rst
- docs/update_ninja_version.rst
- noxfile.py
- pyproject.toml
- setup.cfg
- setup.py
This removes `test_requires` and `setup_requires`, as they are deprecated. This also adds nox, making it easier for new contributors to get started, as well as simplifying some tasks. Bumping to the latest version can now be done with `nox -s bump`!
> chore: add nox and remove deprecated things

- .github/workflows/build.yml
- pyproject.toml
release notes: https://github.com/pypa/cibuildwheel/releases/tag/v2.0.0
> chore: update cibuildwheel from 2.0.0a4 to 2.0.0

- noxfile.py
Running `nox` fails from a clean repo without this.
> fix: create dist folder if it does not exist

- .github/workflows/build.yml
There's a race condition in the jobs meaning `dist` will be populated by the the sdist and any number of wheels. If there's more than one wheel, sdist tests will fail.
We do not require tests in test_distribution.py which are meant for local builds.
Rather than excluding these tests, simply do not provide a `dist` folder to look at. It keeps the workflow simple and if anyone tries to reproduce locally they will run these tests which are meant to be run locally.
> fix(ci): test_sdist shall not test wheels installation

- .github/workflows/build.yml
- CMakeLists.txt
- NinjaUrls.cmake
- docs/update_ninja_version.rst
- noxfile.py
- scripts/update_ninja_version.py
- setup.cfg
This helps not to depend on upstream builds given we were already building almost all from sources with the exception of macOS build and Windows x86_64 build.
see also #41
> Always build from sources

- .github/workflows/build.yml
- noxfile.py
- pyproject.toml
- scripts/repair_wheel.py
Fixes #35 & #41 
Depends on #61 & #62
> feat: add universal2 support

- .github/workflows/build.yml
This now builds musllinux wheels.
> chore(ci): use cibuildwheel 2.2.0a1

- scripts/repair_wheel.py
> fix: add tag for macOS x86_64

- CMakeLists.txt
- scripts/repair_wheel.py
ExternalProject_add does not forward CMAKE_OSX_ARCHITECTURES to the external project. This leads to a broken universal2 build which only has the x86_64 binary.
Let's forward a few variables to the external project to fix this and add a test.
Fix #88
> fix: universal2 build

- setup.py
Identical fix to https://github.com/scikit-build/cmake-python-distributions/pull/175
I've noticed that piwheels is unable to build ninja wheels due to the same problem that was reported for cmake in https://github.com/scikit-build/cmake-python-distributions/issues/171
> fix: non-isolated build fails when versioneer is installed

- MANIFEST.in
- pyproject.toml
- setup.py
- src/ninja/__init__.pyi
> feat: add typing info

- setup.py
This makes it easier to navigate to the source of the actual PyPI project rather than the ninja project itself. I personally often use the project URLs in the sidebar and find it helpful to be able to go to the actual source of the package for one reason or another. Similar to: https://github.com/scikit-build/cmake-python-distributions/pull/133
> Add project URLs

- CMakeLists.txt
This PR is for OS400 system support. Can anybody kindly help to review and merge it? thanks. 
"configure.py" is deprecated in ninja-build project, and it does not support OS400 system.
> Support OS400 system

- setup.py
Issue found doing a diff between PyPI wheels and wheels in #139
> fix: missing delimiter in trove classifiers definition

- CMakeLists.txt
- pyproject.toml
Following https://github.com/scikit-build/ninja-python-distributions/pull/139#pullrequestreview-1111419421, run Ninja test suite as part of the build
In #139 review, I focused on the diff only. With the full picture when adding tests, it seems that we can follow the same build workflow for Linux & macOS/Windows.
#139 effectively bumped the minimum CMake version to 3.15 (the one required by Ninja itself), so this was bumped here as well.
> chore: run ninja test suite as part of the build

- src/ninja/__init__.py
This is needed for things like jobserver support using the installed "ninja" shortcut. Which is why this is a fork in the first place... See scikit-build/cmake-python-distributions#290.
> fix: allow access to file descriptors

- .github/workflows/build.yml
We are getting warnings about things like node 12 being removed soon.
similar to https://github.com/scikit-build/cmake-python-distributions/pull/305
> chore(deps): GHA updates

- NinjaUrls.cmake
- README.rst
- docs/update_ninja_version.rst
- tests/test_distribution.py
Created by update_ninja_version.py
> Update to Ninja 1.11.1.g95dee.kitware.jobserver-1

- pyproject.toml
This reduces the size of the wheels & installed binaries on musllinux.
> chore(wheels): link libstdc++/libgcc statically on musllinux

- .github/workflows/build.yml
- pyproject.toml
For some reason, the ninja binary built on manylinux1 is segfaulting on ubuntu20.04+ & RHEL 8+. Statically linking libstdc++ fixes the issue.
fixes #157
> fix(wheels): link libstdc++ statically on manylinux1

- .pre-commit-config.yaml
- pyproject.toml
- scripts/convert_to_generic_platform_wheel.py
- scripts/update_ninja_version.py
- setup.cfg
- src/ninja/__init__.py
- tests/test_ninja.py
Should stop pre-commit from trying to upgrade pyupgrade!
> chore: switch to ruff

- .github/workflows/build.yml
`actions/setup-python` [removed python 2.7](https://github.com/actions/setup-python/issues/672) in all versions of the action.
Use Ubuntu provided python 2.7 to continue testing.
PS: I don't mind dropping python2.7 to build ninja wheel but, IMHO, as long as the wheel is built with python 2 compatibility we should at least test the wheel with python 2.7
> chore: continue testing with python 2.7

- .github/workflows/build.yml
Change adapted from:
* https://github.com/scikit-build/cmake-python-distributions/pull/366
Corresponding publisher also added on `PyPI`
> chore: use trusted publisher deployment

- MANIFEST.in
- pyproject.toml
- setup.cfg
- setup.py
`versioneer` was removed in https://github.com/scikit-build/ninja-python-distributions/pull/170
> chore: remove `versioneer` related code from `setup.py`

- .github/workflows/build.yml
python 3.7 is not available on ubuntu-latest
> fix(ci): test sdist on ubuntu-22.04

- .pre-commit-config.yaml
add a lower bound for validate-pyproject-schema-store in order to invalidate pre-commit-ci cache.
> fix: pre-commit-ci

- .github/workflows/build.yml
- pyproject.toml
> chore: run `pip check` as part of tests

- .github/workflows/build.yml
- _build_backend/backend.py
- pyproject.toml
fix #274 
Ninja shall never request ninja in its build dependencies as a default behavior.
When scikit-build-core knows a ninja binary wheel exists for a given platform, it's always added as a dependency when a valid one is not found on the system.
Let's allow ninja to depend on ninja only if explicitly allowed (this will speed-up the CI here). In other cases, it's more likely that a request to build ninja would be because of a forced source only build.
> fix: build from sources with `--no-binary=ninja`

- .github/workflows/build.yml
Speed-up build.
This also updates ubuntu-22.04 to ubuntu-24.04 (or latest) where it does make sense.
> ci(linux): use GHA ARM runners to build ARM wheels

- .coveragerc
- noxfile.py
- pyproject.toml
- fix: remove unused options from pytest
coverage is removed altogether as it's not working
this fixes the linter issue.
- fix: macOS build using nox
With the move from scikit-build to scikit-build-core, the macOS build options need to be updated.
> fix: linter issues & nox macOS build

- .github/workflows/build.yml
- .pre-commit-config.yaml
- noxfile.py
- pyproject.toml
similar too https://github.com/scikit-build/cmake-python-distributions/pull/589
> chore: use dependency-groups

- .github/workflows/build.yml
- .gitmodules
- CMakeLists.txt
- README.rst
- docs/update_ninja_version.rst
- noxfile.py
- pyproject.toml
- scripts/update_ninja_version.py
- tests/test_ninja.py
Jobserver now upstreamed, so using upstream release!
> feat: use 1.13.0 official release

- CMakeLists.txt
Following 7a70669 ("feat: use a submodule for ninja sources (#278)", 2025-03-20), attempting to fetch sources is not required as sources are already expected to be available.
> chore: Simplify build-system replacing FetchContent calls with add_subdirectory

- .github/workflows/build.yml
- pyproject.toml
This PR adds riscv64 linux wheels now that they can be uploaded to PyPI.
> feat: add riscv64 linux wheels

- .github/workflows/build.yml
> ci: split QEMU builds

- .gitmodules
- README.rst
- docs/update_ninja_version.rst
- pyproject.toml
- tests/test_ninja.py
Ran `nox -s bump -- --upstream-repository Kitware/ninja`.
The Kitware fork adds the following feature compared to upstream:
- `make-4.3-jobserver-1`: Based on [this release](https://github.com/digit-google/ninja/releases/tag/JOBSERVER-with-pipe-support), which includes pipe-based jobserver support for Make 4.3 and was conveniently created by the same developer who upstreamed jobserver support
> feat: use 1.13.0 from Kitware fork

- .github/workflows/build.yml
- README.rst
- pyproject.toml
backport work done in #301 now that cibuildwheel has been updated in master
@henryiii said
> @mayeut, @jcfr, what should we do here:
> Move to using manylinux_2_28 (cibuildwheel default)
> Move to using manylinux_2014
> Keep manylinux_2010 (fully specify)
> And
> Move to using musllinux_1_2 (cibuildwheel default)
> Keep musllinux_1_1 (fully specify)
> And
> Move to requiring Python 3.8+ (might be best if increasing manylinux?)
> Keep 3.7+ (we don't actually depend on Python at all, but 3.7 users might need older platforms)
> ?
> (I think I like 2014 + 1_2 + 3.8+, though a step more modern is 2_28 + 1_2 + 3.8+ and a step less modern is 2014 + 1_2 + 3.7+ )
> And should we do this for 1.13 or after?
@mayeut replied
> I think I like 2014 + 1_2 + 3.8+ too. It's probably a bit too soon to move …
> break: drop Python 3.7, manylinux2010 & musllinux_1_1
